name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Using default versions of Java, Go and Node, override if needed
      # - uses: actions/setup-java@v1.3.0
      # - uses: actions/setup-go@v1.0.0
      # - uses: actions/setup-node@v1.1.0

      # - uses: actions/setup-python@v1
      #   with:
      #     python-version: '^3.7'

      - name: Setup virtualenv
        run: |
          pip3 install --upgrade pip
          pip3 install setuptools
          pip3 install virtualenv
          sudo ln -s $(which virtualenv) /usr/local/bin/virtualenv

      - name: Build
        run: ./pleasew build //...
      
      - name: Test
        run: ./pleasew test //...

        # env:
        #   PLZ_OVERRIDES: cache.dir:${{ env.GITHUB_WORKSPACE }}/.cache/please
        #   GOCACHE: ${{ env.GITHUB_WORKSPACE }}/.cache/gocache
        #   GOPATH: ${{ env.GITHUB_WORKSPACE }}/.cache/gopath
        #   YARN_CACHE_FOLDER: ${{ env.GITHUB_WORKSPACE }}/.cache/yarn
        #   PIP3_CACHE_FOLDER: ${{ env.GITHUB_WORKSPACE }}/.cache/pip3
