name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Install virtualenv
        run: |
          pip3 install --upgrade pip
          pip3 install setuptools
          pip3 install virtualenv
          ln -s $(which virtualenv) /usr/local/bin/virtualenv

      - name: Build
        run: ./pleasew build //...
        # env:
        #   PLZ_OVERRIDES: cache.dir:${{ env.GITHUB_WORKSPACE }}/.cache/please
        #   GOCACHE: ${{ env.GITHUB_WORKSPACE }}/.cache/gocache
        #   GOPATH: ${{ env.GITHUB_WORKSPACE }}/.cache/gopath
        #   YARN_CACHE_FOLDER: ${{ env.GITHUB_WORKSPACE }}/.cache/yarn
        #   PIP3_CACHE_FOLDER: ${{ env.GITHUB_WORKSPACE }}/.cache/pip3
