name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install virtualenv
        run: |
          pip3 install setuptools virtualenv

      - name: Build
        run: ./pleasew build //...
        # env:
        #   PLZ_OVERRIDES: cache.dir:${{ env.GITHUB_WORKSPACE }}/.cache/please
        #   GOCACHE: ${{ env.GITHUB_WORKSPACE }}/.cache/gocache
        #   GOPATH: ${{ env.GITHUB_WORKSPACE }}/.cache/gopath
        #   YARN_CACHE_FOLDER: ${{ env.GITHUB_WORKSPACE }}/.cache/yarn
        #   PIP3_CACHE_FOLDER: ${{ env.GITHUB_WORKSPACE }}/.cache/pip3
